[wokwi]
version=1
firmware = 'E:/Git/Motors_simulation/Servo_Motors/.pio/build/esp32doit-devkit-v1/firmware.bin'
elf= 'E:/Git/Motors_simulation/Servo_Motors/.pio/build/esp32doit-devkit-v1/firmware.elf'